@extends('pages.layout.app')
@section('content')

    <section class="page-banner "  style="background-image:url('images/fortis-1-color-1800x700.jpg');" ">
    <div class="row">
        <div class="small-12 medium-10 medium-centered columns">
            <div class="page-banner-content"id="page-banner-content">
                <h1>Terms and Conditions</h1>


                <p></p>

                <!-- End if page sub nav -->


                <!-- End if page builder -->


            </div>
        </div>
    </div>
    </section>
    <!-- End check that page is not home or front -->


    <a class="section-anchor" id="section-1"></a>
    <section class="section-bg content_section  white " style="">

        <section class="content-section wow fadeIn">
            <div class="row">

                <div class="small-12 columns medium-12 ">
                    <p class="p2"><span class="s1">PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY. BY ACCESSING THIS WEBSITE YOU AGREE TO BE BOUND BY THE TERMS AND CONDITIONS BELOW. THESE TERMS AND CONDITIONS ARE SUBJECT TO CHANGE. ANY CHANGES WILL BE INCORPORATED INTO THE TERMS AND CONDITIONS POSTED TO THIS WEBSITE FROM TIME TO TIME. IF YOU DO NOT AGREE WITH THESE TERMS AND CONDITIONS, PLEASE DO NOT ACCESS THIS WEBSITE.</span></p>
                    <p class="p2"><span class="s1">Unauthorized use of Nestlecity International&#8217;s Website and systems, including but not limited to unauthorized entry into Nestlecity International&#8217;s systems, misuse of passwords, or misuse of any information posted to a site, is strictly prohibited and may subject individuals to criminal prosecution.</span></p>
                    <p class="p2"><span class="s1">You acknowledge that {{ env('APP_NAME') }}may disclose and transfer any information that you provide through this Website to (i) its subsidiaries, affiliates, agents or information providers; (ii) any other person or entity with your consent; or (iii) if we have a right or duty to disclose or are permitted or compelled to so disclose such information by law. You consent to the transmission, transfer or processing of such information to, or through, any country in the world, as we deem necessary or appropriate (including to countries outside the EEA), and by using and providing information through this Website you agree to such transfers. Use of this Website, including any patterns or characteristics concerning your interaction with it, may be monitored, tracked and recorded. Anyone using this Website expressly consents to such monitoring, tracking and recording.</span></p>
                    <p class="p2"><span class="s1">You agree not to attempt to log on to the Website from any country under sanctions by the Office of Foreign Assets Control (OFAC). Information regarding which countries are under sanctions may be obtained on the U.S. Department of the Treasury website. Any attempt to log on to the Website from one of these countries may result in your access being restricted or terminated.</span></p>
                    <p class="p2"><span class="s1">If you use Nestlecity International’s Website or systems to access data related to any accounts of which you are not the owner or authorized user as reflected in Nestlecity International’s systems, you shall indemnify, defend, and hold harmless {{ env('APP_NAME') }}and all of its direct and indirect subsidiaries, affiliates, officers, directors, employees, agents, successors, and assigns from any and all losses, liabilities, damages, and all related costs and expenses, arising from, relating to, or resulting (directly or indirectly) from such access. Further, without limiting Nestlecity International’s rights or your obligations under any other provision of these Terms and Conditions, and notwithstanding the same, in the event of any actual or reasonably suspected unauthorized access to the personal information of a customer (including but not limited to customer names, addresses, phone numbers, bank and credit card account numbers, income and credit histories, and social security numbers) under your control or subsequent to and arising from your past exercise of control, direct damages in connection with any such breach will include the cost and expenses of investigation and analysis (including by law firms and forensic firms), correction or restoration of any destroyed, lost or altered data, notification to affected customers, offering and providing of credit monitoring, customers service, or other remediation services, and any related cost. Nestlecity International’s rights to indemnity under this section are in addition to all other rights and remedies available at Law or in equity. Any exercise by {{ env('APP_NAME') }}of its rights to indemnification shall be without prejudice to such other rights and remedies. You manifest your assent to this indemnity by accessing account data through Nestlecity International’s Website or systems, notwithstanding the terms of any agreement you have with a customer or an account owner stating otherwise. This indemnity includes but is not limited to losses associated with (1) a data breach of your systems and (2) a data breach of the systems of any person or entity with whom you provided or shared {{ env('APP_NAME') }}customer account data.</span></p>
                    <p class="p3"><strong><span class="s1">Copyright Notices</span></strong></p>
                    <p class="p2"><span class="s1">The works of authorship contained in this Website, including but not limited to all design, text, sound recordings and images, are owned, except as otherwise expressly stated, by {{ env('APP_NAME') }}or one of its subsidiaries or affiliates. Except as otherwise expressly stated herein, they may not be copied, transmitted, displayed, performed, distributed (for compensation or otherwise), licensed, altered, framed, stored for subsequent use or otherwise used in whole or in part in any manner without Nestlecity International’s prior written consent, except to the extent permitted by the Copyright Act of 1976 (17 U.S.C. § 107), as amended, and then, only with notices of Nestlecity International’s proprietary rights provided that you may download information and print out hard copies for your personal use, so long as you do not remove any copyright or other notice as may be contained in information, as downloaded.</span></p>
                    <p class="p3"><strong><span class="s1">Trademark Notices</span></strong></p>
                    <p class="p2"><span class="s1">“Nestlecity International” and the {{ env('APP_NAME') }}logo are trademarks of Nestlecity International. Other featured words or symbols, used to identify the source of goods and services, may be the trademarks of their respective owners.</span></p>
                    <p class="p3"><strong><span class="s1">Web Content and Materials</span></strong></p>
                    <p class="p2"><span class="s1">The information on this Website is for information purposes only. It is believed to be reliable, but {{ env('APP_NAME') }}does not warrant its completeness, timeliness or accuracy. The information on the Website is not intended as an offer or solicitation for the purchase of any security or any financial instrument.</span></p>
                    <p class="p2">SECURITIES (INCLUDING MUTUAL FUNDS AND VARIABLE LIFE INSURANCE), ANNUITIES AND INSURANCE PRODUCTS ARE NOT BANK DEPOSITS AND ARE NOT INSURED BY THE FDIC OR ANY OTHER AGENCY OF THE UNITED STATES, NOR ARE THEY OBLIGATIONS OF, NOR INSURED OR GUARANTEED BY, {{ env('APP_NAME') }}OR ITS AFFILIATES. SECURITIES (INCLUDING MUTUAL FUNDS AND VARIABLE LIFE INSURANCE) AND ANNUITIES INVOLVE INVESTMENT RISKS, INCLUDING THE POSSIBLE LOSS OF VALUE.</p>
                    <p class="p2"><span class="s1">The information and materials contained in this Website-and the terms and conditions of the access to and use of such information and materials-are subject to change without notice. Products and services described, as well as, associated fees, charges, interest rates, and balance requirements may differ among geographic locations. Not all products and services are offered at all locations.</span></p>
                    <p class="p2"><span class="s1">Certain portions or pages of this Website may be subject to additional disclosures and disclaimers. In the event of a conflict between those disclosures and disclaimers, and these terms and conditions, the additional disclosures and disclaimers will govern for those portions or pages.</span></p>
                    <p class="p2"><span class="s1">You agree that: (i) you will not engage in any activities related to the Website that are contrary to applicable law, regulation or the terms of any agreements you may have with Nestlecity International; and (ii) in circumstances where locations of the Website require identification for process, you will establish commercially reasonable security procedures and controls to limit access to your password or other identifying information to authorized individuals.</span></p>
                    <p class="p2"><span class="s1">{{ env('APP_NAME') }}OR ITS SUPPLIERS MAY DISCONTINUE OR MAKE CHANGES IN THE INFORMATION, PRODUCTS OR SERVICES DESCRIBED HEREIN AT ANY TIME WITHOUT PRIOR NOTICE TO YOU AND WITHOUT ANY LIABILITY TO YOU UNLESS REQUIRED BY LAW. ANY DATED INFORMATION IS PUBLISHED AS OF ITS DATE ONLY, AND {{ env('APP_NAME') }}DOES NOT UNDERTAKE ANY OBLIGATION OR RESPONSIBILITY TO UPDATE OR AMEND ANY SUCH INFORMATION. {{ env('APP_NAME') }}RESERVES THE RIGHT TO TERMINATE ANY OR ALL WEBSITE OFFERINGS OR TRANSMISSIONS WITHOUT PRIOR NOTICE TO THE USER UNLESS REQUIRED BY LAW. FURTHERMORE, BY OFFERING THIS WEBSITE AND INFORMATION, PRODUCTS OR SERVICES VIA THIS WEBSITE, NO DISTRIBUTION OR SOLICITATION IS MADE BY {{ env('APP_NAME') }}TO ANY PERSON TO USE THE WEBSITE OR SUCH INFORMATION, PRODUCTS OR SERVICES IN JURISDICTIONS WHERE THE PROVISION OF THE WEBSITE AND SUCH INFORMATION, PRODUCTS OR SERVICES IS PROHIBITED BY LAW.</span></p>
                    <p class="p3"><strong><span class="s1">Potential Disruption of Service</span></strong></p>
                    <p class="p2"><span class="s1">Access to the Website may from time to time be unavailable, delayed, limited or slowed due to, among other things:</span></p>
                    <p class="p4"><span class="s1">Hardware failure, including among other things failures of computers (including your own computer), servers, networks, telecommunication lines and connections, and other electronic and mechanical equipment.</span></p>
                    <p class="p4"><span class="s1">Software failure, including among other things, bugs, errors, viruses, botnets, configuration problems, incompatibility of systems, utilities or applications, the operation of firewalls or screening programs, unreadable codes, or irregularities within particular documents or other content.</span></p>
                    <p class="p4"><span class="s1">Overload of system capacities.</span></p>
                    <p class="p4"><span class="s1">Damage caused by severe weather, earthquakes, wars, insurrection, riots, civil commotion, act of God, accident, fire, water damage, explosion, mechanical breakdown or natural disasters.</span></p>
                    <p class="p4"><span class="s1">Interruption (whether partial or total) of power supplies or other utility of service.</span></p>
                    <p class="p4"><span class="s1">Strike or other stoppage (whether partial or total) of labor.</span></p>
                    <p class="p4"><span class="s1">Governmental or regulatory restrictions, exchange rulings, court or tribunal orders or other human intervention.</span></p>
                    <p class="p4"><span class="s1">Any other cause (whether similar or dissimilar to any of the foregoing) whatsoever beyond the control of Nestlecity International.</span></p>
                    <p class="p3"><strong><span class="s1">Links to Other Sites</span></strong></p>
                    <p class="p2"><span class="s1">Links to non-{{ env('APP_NAME') }}Websites are provided solely as pointers to information on topics that may be useful to the Websites, and {{ env('APP_NAME') }}has no control over the content on such non-{{ env('APP_NAME') }}Websites. If you choose to follow a link to a Website not controlled by Nestlecity International, {{ env('APP_NAME') }}makes no warranties, either express or implied, concerning the content of such site, including the accuracy, completeness, reliability or suitability thereof for any particular purpose, nor does {{ env('APP_NAME') }}warrant that such site or content is free from any claims of copyright, trademark or other infringement of the rights of third parties or that such site or content is devoid of viruses or other contamination. {{ env('APP_NAME') }}does not guarantee the authenticity of documents on the Internet. Links to non-{{ env('APP_NAME') }}sites do not imply any endorsement of or responsibility for the opinions, ideas, products, information or services offered at such sites, or any representation regarding the content at such sites.</span></p>
                    <p class="p3"><strong><span class="s1">LIMITATION OF LIABILITY</span></strong></p>
                    <p class="p2"><span class="s1">BECAUSE OF THE POSSIBILITY OF HUMAN AND MECHANICAL ERROR AS WELL AS OTHER FACTORS, THE WEBSITE (INCLUDING ALL INFORMATION AND MATERIALS CONTAINED ON THE WEBSITE) IS PROVIDED “AS IS” “AS AVAILABLE”. {{ env('APP_NAME') }}AND THIRD PARTY DATA PROVIDERS ARE NOT PROVIDING ANY WARRANTIES AND REPRESENTATIONS REGARDING THE WEBSITE. {{ env('APP_NAME') }}AND THIRD PARTY DATA PROVIDERS DISCLAIM ALL WARRANTIES AND REPRESENTATIONS OF ANY KIND WITH REGARD TO THE WEBSITE, INCLUDING ANY IMPLIED WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT OF THIRD PARTY RIGHTS, FREEDOM FROM VIRUSES OR OTHER HARMFUL CODE, OR FITNESS FOR ANY PARTICULAR PURPOSE. FURTHER, {{ env('APP_NAME') }}WILL NOT BE LIABLE FOR ANY DELAY, DIFFICULTY IN USE, INACCURACY OF INFORMATION, COMPUTER VIRUSES, MALICIOUS CODE OR OTHER DEFECT IN THIS WEBSITE, OR FOR THE INCOMPATIBILITY BETWEEN THIS WEBSITE AND FILES AND THE USER&#8217;S BROWSER OR OTHER SITE ACCESSING PROGRAM. NOR WILL {{ env('APP_NAME') }}BE LIABLE FOR ANY OTHER PROBLEMS EXPERIENCED BY THE USER DUE TO CAUSES BEYOND Nestlecity International&#8217;S CONTROL. NO LICENSE TO THE USER IS IMPLIED IN THESE DISCLAIMERS.</span></p>
                    <p class="p2"><span class="s1">{{ env('APP_NAME') }}AND THIRD PARTY DATA PROVIDERS DO NOT WARRANT THE ACCURACY, ADEQUACY, OR COMPLETENESS OF THE INFORMATION AND MATERIALS CONTAINED ON THE WEBSITE AND EXPRESSLY DISCLAIMS LIABILITY FOR ERRORS OR OMISSIONS IN THE MATERIALS AND INFORMATION. FURTHERMORE, {{ env('APP_NAME') }}AND ITS AFFILIATES WILL NOT BE LIABLE FOR ANY DELAY, DIFFICULTY IN USE, COMPUTER VIRUSES, MALICIOUS CODE, OR OTHER DEFECT IN WEBSITE, ANY INCOMPATIBILITY BETWEEN THE WEBSITE AND THE USER&#8217;S FILES AND THE USER&#8217;S BROWSER OR OTHER SITE ACCESSING PROGRAM, OR ANY OTHER PROBLEMS EXPERIENCED BY THE USER DUE TO CAUSES BEYOND {{ env('APP_NAME') }}AND ITS AFFILIATES&#8217; CONTROL. NO LICENSE TO THE USER IS IMPLIED IN THESE DISCLAIMERS. NOTHING HEREIN SHALL BE CONSTRUED AS LIMITING OR REDUCING Nestlecity International&#8217;S RESPONSIBILITIES AND OBLIGATIONS TO CLIENTS IN ACCORDANCE WITH APPLICABLE LAWS AND REGULATIONS.</span></p>
                    <p class="p2"><span class="s1">UNDER NO CIRCUMSTANCES WILL {{ env('APP_NAME') }}BE LIABLE FOR ANY LOST PROFITS, LOST OPPORTUNITY OR ANY INDIRECT, CONSEQUENTIAL, INCIDENTAL, SPECIAL, PUNITIVE, OR EXEMPLARY DAMAGES ARISING OUT OF ANY USE OF OR INABILITY TO USE THE WEBSITE OR ANY PORTION THEREOF, REGARDLESS OF WHETHER {{ env('APP_NAME') }}HAS BEEN APPRISED OF THE LIKELIHOOD OF SUCH DAMAGES OCCURRING AND REGARDLESS OF THE FORM OF ACTION, WHETHER IN CONTRACT, WARRANTY, TORT, (INCLUDING NEGLIGENCE), STRICT LIABILITY, OR OTHERWISE.</span></p>
                    <p class="p3"><strong><span class="s1">Enforceability and Governing Law</span></strong></p>
                    <p class="p2"><span class="s1">In the event any of the terms or provisions of these Terms and Conditions shall be held to be unenforceable, the remaining terms and provisions shall be unimpaired and the unenforceable term or provision shall be replaced by such enforceable term or provision as comes closest to the intention underlying the unenforceable term or provision. These Terms and Conditions shall be subject to any other agreements you have entered into with Nestlecity International. </span></p>
                    <p class="p5"><strong><span class="s1">Contact Us</span></strong></p>
                    <p class="p5"><span class="s1">If you have any questions or comments about this Website or these Terms and Conditions, we encourage you to contact our customer service department by completing our <a href="contact.html"><span class="s2">online email form</span></a> or by calling +1 332 205 6688 or +44 208 040 4435. </span></p>
                    <p class="p5"><span class="s1">In the event you notice suspicious activity on your account or believe your personal ID, password or PIN has been compromised, please contact us immediately. </p>
                </div>
                </article>
        </section>

    </section>


    <section class="consultation-cta">
        <div class= "row medium-collapse full-width" data-equalizer data-equalize-on="medium">
            <div class="small-12 medium-7 columns consultation-cta-left" data-equalizer-watch>
                <p x-ms-format-detection="none">Interested in banking with us? Call +1 332 205 6688 or +44 208 040 4435</p>
            </div>
            <a href="contact.html"  class="small-12 medium-5 columns consultation-cta-right"  data-equalizer-watch>
                <p>Request a Consultation</p>
            </a>
        </div>
    </section>


@endsection
